# Generated by Django 3.2.3 on 2021-07-09 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_auto_20210709_2337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='iddd',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
