# Generated by Django 3.1.2 on 2021-07-09 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0002_matching_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fieldnamd', models.CharField(max_length=20)),
            ],
        ),
    ]
