# Generated by Django 3.1.2 on 2021-07-09 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0003_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='field',
            old_name='fieldnamd',
            new_name='fieldname',
        ),
        migrations.CreateModel(
            name='midField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('midfieldname', models.CharField(max_length=20)),
                ('fieldnameId', models.ForeignKey(db_column='fieldnameId', on_delete=django.db.models.deletion.CASCADE, to='Project.field')),
            ],
        ),
        migrations.CreateModel(
            name='lastField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastfieldname', models.CharField(max_length=20)),
                ('fieldnameId', models.ForeignKey(db_column='fieldnameId', on_delete=django.db.models.deletion.CASCADE, to='Project.field')),
                ('midfieldnameId', models.ForeignKey(db_column='midfieldnameId', on_delete=django.db.models.deletion.CASCADE, to='Project.midfield')),
            ],
        ),
    ]
