# Generated by Django 3.2.3 on 2021-07-10 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0005_auto_20210710_0053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='type',
            new_name='activity',
        ),
    ]
