# Generated by Django 3.2.3 on 2021-07-10 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0006_rename_type_club_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='field',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
