# Generated by Django 3.2.3 on 2021-07-10 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0008_remove_club_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='clubfield',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
